name: Build Test Publish
on: push

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install and upgrade pip, setuptools and wheel
        run: python -m pip install --user --upgrade pip setuptools wheel

      - name: Install packages needed for testing and building
        run: python -m pip install --user tensorflow numpy scipy

      - name: Run tests
        run: python -m unittest discover tests

      - name: Install sphinx
        if: contains(github.ref, "master")
        run: python -m pip install --user sphinx sphinx-markdown-builder

      - name: Run sphinx
        if: contains(github.ref, "master")
        run: sphinx-apidoc -o sphinx-docs tfga sphinx-apidoc --full -A "Robin 'Tora' Kahlow" && cd sphinx-docs && make markdown

      - name: Upload documentation to wiki
        if: contains(github.ref, "master")
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "sphinx-docs/_build/markdown"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.gh_personal_access_token }}

      - name: Build dist
        run: python setup.py sdist bdist_wheel

      - name: Publish to test PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
