name: pypi-publish
on: push

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Set up setuptools and wheel
        run: python -m pip install --user --upgrade setuptools wheel

      - name: Build dist
        run: python setup.py sdist bdist_wheel

      - name: Publish to test PyPI
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
